[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/_stcore/health"
restartPolicyType = "never"

[env]
PORT = "8080"
PYTHONUNBUFFERED = "1"
STREAMLIT_SERVER_HEADLESS = "true"
STREAMLIT_SERVER_ENABLE_CORS = "false"